### ISSUE TITLE
Change fonts 

### ISSUE THREAD

**Issue by biopig** [mdbaron42/pyBoxshade#11]
I find in the file OutDevs.py, I get the fonts set for Courier-Bold. Then how can I set the fonts to Times New Roman for ps. format output.

**Comment by mdbaron42** [comment]
If you change the font, you should use a monospaced font or the alignment will look all wrong. If you use Times New Roman, for example, the spacing of the letters in the sequence names will look wrong, because the program places them one at a time, evenly spaced. Some of the letters in the alignment may be too wide, as well, as in this mini alignment where the TimesNewRoman "M" is much wider than the other letters, and does not fit in the space allocated for each letter. For obvious reasons, an alignment of protein or DNA has to have the letters in columns, and each column has to have the same width.
![image](https://user-images.githubusercontent.com/64478709/111076103-de2e8c80-84e2-11eb-9dfa-cd6440b1b493.png)

If you desperately want to have this other font, the quickest way is to edit the PS file with a text editor, changing all mentions of "Courier-Bold" to "TimesNewRomanPSMT" (at least that is the PostScript name of that font on my computer, may be different for yours). If you want the bold version, it would be TimesNewRomanPS-BoldMT.

If I get a lot of requests, I will add the ability to choose the font, but it would mean adding code to interrogate each system for the available monospace fonts (most computers have Courier or Courier New, but after that every system is different), and then adjusting the output spacing to allow for the small variations in each one.

Hope this helps
Michael
